version: '3'

services:
  autostop.services.maps:
    image: autostop.services.maps
    build:
      context: .
      dockerfile: Services/Autostop.Services.Maps/Dockerfile

  autostop.services.identity:
    image: autostop.services.identity
    build:
      context: .
      dockerfile: Services/Autostop.Services.Identity/Dockerfile


  autostop.services.estimates:
    image: autostop.services.estimates
    build:
      context: .
      dockerfile: Services/Autostop.Services.Estimates/Dockerfile


  autostop.services.rides:
    image: autostop.services.rides
    build:
      context: .
      dockerfile: Services/Autostop.Services.Rides/Dockerfile

  autostop.web.admin:
    image: autostop.web.admin
    build:
      context: .
      dockerfile: Web Apps/Autostop.Web.Admin/Dockerfile

